version: '3.8'
services:
  ml_api:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "5001:5000"   # expose webserver to localhost host:container
    command: bash -c "make run-service-development"
