version: '3.8'
services:
  webapp:
    build: .
    container_name: webapp
    expose:
      - 5000
    ports:
      - "5005:5000"
    volumes:
      - ./:/application

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./config/prometheus/:/etc/prometheus/  # path on the host, relative to the compose file
      - prometheus_data:/prometheus  # named volume
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    expose:
      - 9090
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=foobar
      - GF_USERS_ALLOW_SIGN_UP=false

volumes:
    prometheus_data:
    grafana_data:
