version: '3.8'
services:
  ml_api:
    build:
      context: ../
      dockerfile: docker_test/Dockerfile
    environment:
      DB_HOST: test_db
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
    depends_on:
      - test_db
    ports:
      - "5001:5000"   # expose webserver to localhost host:container
    command: bash -c "make run-service-development"

  test_db:
    image: postgres:15
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - my_db_data_test:/var/lib/postgresql/data

volumes:
  my_db_data_test:
